# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slurmnbs',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/slurmnbs',
                'lib_path': 'slurmnbs'},
  'syms': {'slurmnbs.core': {'slurmnbs.core.foo': ('core.html#foo', 'slurmnbs/core.py')}}}
